load(
    "//bazel:coevent_build_system.bzl",
    "coevent_catch_test",
    "coevent_package",
)

coevent_package()

coevent_catch_test(
    name = "endpoint_test",
    srcs = [
        "endpoint_test.cc",
    ],
)
