load(
    "//bazel:coevent_build_system.bzl",
    "coevent_cc_library",
    "coevent_package",
)

coevent_package()

coevent_cc_library(
    name = "task_lib",
    hdrs = [
        "task.h",
    ],
)
